FROM registry.fedoraproject.org/fedora:38

RUN dnf install -y dnf-plugins-core && \
dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo && \
dnf install -y ansible terraform which jq
